# This workflow will generate a distribution and upload it to PyPI

name: Publish Alpha Build
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'sj201_interface/version.py'

jobs:
  publish_alpha_release:
    uses: neongeckocom/.github/.github/workflows/publish_alpha_release.yml@master
    secrets: inherit
    with:
      version_file: "sj201_interface/version.py"
      publish_prerelease: true
      update_changelog: true